#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
chmod a+x ${OPENSHIFT_REPO_DIR}/diy/runapp.py
nohup ${OPENSHIFT_REPO_DIR}/diy/runapp.py > ${OPENSHIFT_LOG_DIR}/runapp.log 2>&1 &

